version: 2
jobs:
  build:
    working_directory: /yonatankoren
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - run:
          name: Build Image 
          command: docker build .
